# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231ca9a62fe9dfba0dce8279f8480d9b48d5e184772620338d04c81c446157bad28ad527ed6b7a5cbf8d1a5fb5d42bb5c8aa21993b87586f4a9e9fef338e1080

test:
  secret_key_base: 237edbad72c015536f032b4fe689f180ad478f942a02ce3486c85e3d7f94c40e17c34fb26c8359836f141171d3d2558aa8708b5317c24eccbbfbde880ff24567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
